#################### version #################################
soft:
  version: 1.0
# ==============启用端口号 server port ============================
server:
  port: 8042
###############################local datasource#########################################
spring:
  data:
    mongodb:
      database: dev
      host: 19.228.12.33
      port: 27019
      username: nxin
      password: 2GBH#WFUUJGkfXGu
# ===============  log  =============================
logging:
  config: classpath:logback-spring.xml